### ISSUE TITLE
Review the feature permission policy header value

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#11]
Proposed configuration for the permission policy header must be reviewed.

Cf discussion thread #10 for the follow-up.

**Comment by righettod** [comment]
Error in commit

**Comment by righettod** [comment]
I close the topic because the [issue](https://github.com/w3c/webappsec-permissions-policy/issues/483) never get replied 😞

**Comment by ecki** [comment]
Since a more generic denied value is rejected, shouldn’t that mean you need to review the list even more often?

**Comment by righettod** [comment]
Yes.
