### ISSUE TITLE
OSHP logo and mantra

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#14]
### Description

See [#13](https://github.com/oshp/oshp-tracking/discussions/13)

### Additional resources

- https://www.librelogos.org/available
- https://looka.com/logo-maker

**Comment by righettod** [comment]
[PR](https://github.com/OWASP/www-project-secure-headers/pull/104) submitted to add logo to the main repo 💯 

[PR](https://github.com/OWASP/owasp-swag/pull/51) submitted to the SWAG repo 😃

**Comment by riramar** [comment]
Thanks!
