### ISSUE TITLE
Protect the project main repo against PR spamming

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#15]
😈 Recently we started receiving [PR spamming](https://github.com/OWASP/www-project-secure-headers/pull/109) on the site repo.

🛡 Find a way to automatically close them using GitHub action workflows.

🌎 References:
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by riramar** [comment]
Hi @righettod 

I was checking and GitHub recommends this https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository but it doesn't seems to be really effective.
I've changed our settings to this:

![image](https://user-images.githubusercontent.com/6748242/206701222-f1f4e129-2ee0-459e-9c19-b99b8a9d0bc1.png)

But I don't think this is going to solve the problem. Do you think we should make this settings more restrictive without impacting the productive?
I also reported https://github.com/IcebergVerse to GitHub as spammer. Maybe you can also report and GitHub ban his account.

Regards
Ricardo Iramar

**Comment by riramar** [comment]
Another option is https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches but I need to take a close look how it works.

**Comment by righettod** [comment]
Hi @righettod ,

Yes, enforce the setting are strict as possible for new users that we do no know. We will then release the access if a situating need this. The amount of contributor allow us to use strictest mode for the moment 😃

**Comment by righettod** [comment]
> Another option is https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches but I need to take a close look how it works.

OK, I will take a look on my side too and we will cross check our both understating later  😃 

To be consistent across the OSHP org projects, we should apply restrictions that the ORG level every time it is possible. What do you think ?

**Comment by riramar** [comment]
> > Another option is https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches but I need to take a close look how it works.
> 
> OK, I will take a look on my side too and we will cross check our both understating later 😃
> 
> To be consistent across the OSHP org projects, we should apply restrictions that the ORG level every time it is possible. What do you think ?

Make sense to me.

**Comment by righettod** [comment]
✅ Current protection enabled seems to be OK so we can close this topic.
