### ISSUE TITLE
Add information about headers in web API context.

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#19]
In the **Best Practices** tab, add a section to indicates which HTTP response headers is useful to add in the context of a web API consumed by a browser.

**Comment by righettod** [comment]
Add, in the following TAB, a dedicated section for **CORS best practices** to prevent security issues:

![image](https://github.com/oshp/oshp-tracking/assets/1573775/046b5f85-602f-4b85-bd15-a5fbe6007709)

**Comment by righettod** [comment]
👨‍💻 I added the following mention via the PR https://github.com/OWASP/www-project-secure-headers/pull/166 :

![image](https://github.com/oshp/oshp-tracking/assets/1573775/b9270d9f-6019-4924-9570-188e7b2fa55c)

📚 It was based on the following justification from a API provider perspective in the context, in which, the API is consume by a browser.

| Header                                | My point of view                                                                                                                             |
|---------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------|
| **Strict-Transport-Security**         | Will ensure that calls will be performed via HTTPS.                                                                                          |
| **X-Frame-Options**                   | Will ensure that calls to an service will not be framed to capture content returned.                                                         |
| **X-Content-Type-Options**            | Will ensure that the browser, consuming the service, will respect the content type specified for the content returned.                       |
| **Content-Security-Policy**           | Will try to prevent, as much as possible, a potential abuse in case in which the content returned was altered at storage level.              |
| **X-Permitted-Cross-Domain-Policies** | Same effect than for a normal web page in case of HTML content returned.                                                                     |
| **Referrer-Policy**                   | Will prevent origin information disclosure if the content returned contains clickable links in case of HTML content type.                    |
| **Cross-Origin-[header]**             | Will try to prevent, as much as possible, usage of the resource from an unexpected domains in case of image or script content type returned. |
| **Permissions-Policy**                | Same effect than for a normal web page in case of HTML content returned.                                                                     |
| **Cache-Control** and **Pragma**      | Prevent caching of the content returned for service using REST style URL.                                                                    |

@riramar Are you OK with my justification?

**Comment by riramar** [comment]
Yes! I'm ok with that.

**Comment by righettod** [comment]
> Yes! I'm ok with that.

✅ Thanks, so, I can close the ticker as processed.
