### ISSUE TITLE
CI job failure: update_monitoring_technical_references_dashboard

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#26]
Hi @riramar ,

Can you manually trigger this worflow:

https://github.com/OWASP/www-project-secure-headers/actions/workflows/monitoring-technical-references-generate-dashboard.yml

The goal is to fix this failure:

![image](https://github.com/oshp/oshp-tracking/assets/1573775/eee6d92d-f98e-45d1-aab8-9b193ed43bdb)

Thanks a lot in advance 😃

**Comment by riramar** [comment]
Trigged manualy.

![image](https://github.com/oshp/oshp-tracking/assets/6748242/9bebb2cf-f53a-44d4-a3f1-2cd4c0059274)

**Comment by righettod** [comment]
Hi @riramar ,

Thanks, I submlitted the PR https://github.com/OWASP/www-project-secure-headers/pull/168 to try to fix the issue.

Please, can you merge the PR and rerun the job ?

Thanks a lot in advance 😃

**Comment by riramar** [comment]
It worked! :)

![image](https://github.com/oshp/oshp-tracking/assets/6748242/7fe62042-6b35-4cd8-9f81-9da8848cc431)

**Comment by righettod** [comment]
Thanks a lot for your help 👍
