### ISSUE TITLE
Deprecated Security Header - Pragma

### ISSUE THREAD

**Issue by baggers27** [oshp/oshp-tracking#28]
BurpSuite recommends adding Cache-Control and Pragma as headers to control caching.  Reviewing the Mozilla docs actually shows Pragma as a deprecated header but it's not mentioned on the OWASP Response Headers page even though Cache-Control does appear.

Given that Cache-Control is listed on the OWASP documentation, is it worth also adding Pragma as a deprecated security header so it's clear?

**Comment by righettod** [comment]
Hi,

Yes, you have 100% right, thanks a lot for raising the point.

It is added to our TODO list now.

Thanks again for raising the problem to us 👍

**Comment by righettod** [comment]
✅ Done via https://github.com/OWASP/www-project-secure-headers/pull/175
