### ISSUE TITLE
New CORS header "Access-Control-Request-Private-Network"

### ISSUE THREAD

**Issue by righettod** [oshp/oshp-tracking#4]
Hi,

Add new CORS header `Access-Control-Request-Private-Network`and related information flow in the section **Miscellaneous**.

🌎 Sources:
- https://portswigger.net/daily-swig/chrome-to-bolster-csrf-protections-with-cors-preflight-checks-on-private-network-requests
- https://developer.chrome.com/blog/private-network-access-update/
- https://wicg.github.io/private-network-access/
- https://github.com/WICG/private-network-access

💬 March 2022 update:

![image](https://user-images.githubusercontent.com/1573775/163720811-ca196bd0-e485-4071-92a8-558bcf4be7a0.png)

💬 June 2022 update:

![image](https://user-images.githubusercontent.com/1573775/171554674-f60e8745-8d07-4ec5-8bf6-b039205c6570.png)

💬 January 2023 update:

![image](https://user-images.githubusercontent.com/1573775/217158707-d8a4b28d-3f6e-4089-916f-685d022d5c83.png)

**Comment by righettod** [comment]
📑 See [here](https://github.com/OWASP/www-project-secure-headers/issues/51) to work until the move of the issue to this repo.

**Comment by righettod** [comment]
The feature is not yet enabled by default in current release of Chrome.

# Chrome version 

![image](https://user-images.githubusercontent.com/1573775/217156750-f8eda41d-1edd-4fff-b2e0-2570632df7fa.png)

# Test setup

![image](https://user-images.githubusercontent.com/1573775/217156508-4a2aae6c-116e-40d6-a4ef-fd8168144498.png)

# Using default Chrome setup

❌ No header `Access-Control-Request-Private-Network` send.

![image](https://user-images.githubusercontent.com/1573775/217156237-e9a34f91-2c2f-4e05-b7d1-2071ae125999.png)

**Comment by riramar** [comment]
Totally agree with you @righettod . Let's wait to Chrome enable the feature by default.

**Comment by riramar** [comment]
Thanks for checking in details. :)

**Comment by righettod** [comment]
> Thanks for checking in details. :)

It is my job as PL and, in addition, I enjoy deep diving into technical stuff to be sure to fully understand how it works 😃

**Comment by righettod** [comment]
📡 Update on 2023-05-07 ([Source](https://developer.chrome.com/blog/private-network-access-update/#timeline)):
![image](https://user-images.githubusercontent.com/1573775/236689610-7a903642-eb07-4680-9eb8-2b0fdd99493f.png)

💬 Current stable release of Chrome is the **113**:
![image](https://user-images.githubusercontent.com/1573775/236689635-e77e4f82-e073-42a2-aff9-52274aadebb8.png)

**Comment by righettod** [comment]
📡 This [issue](https://github.com/WICG/private-network-access/issues/110) give a status:

![image](https://github.com/oshp/oshp-tracking/assets/1573775/8dc3ffa8-b545-45cc-be74-5978af02f889)

**Comment by righettod** [comment]
PR https://github.com/OWASP/www-project-secure-headers/pull/154 linked
